# MPV configuration file

# Playback Core
profile=gpu-hq
vo=gpu-next
hwdec=auto-safe

# Streaming / Network
cache=yes

# Dithering
deband=yes
deband-iterations=2
deband-threshold=35
deband-range=16
deband-grain=5

dither-depth=10
dither=fruit

# SDR -> HDR
target-peak=100
inverse-tone-mapping=yes
target-colorspace-hint=yes
target-prim=bt.2020
target-trc=pq

# Anime4K
glsl-shaders=~~/shaders/Anime4K_v4.0/Anime4K_Restore_CNN_L.glsl:~~/shaders/Anime4K_v4.0/Anime4K_Upscale_CNN_x2_L.glsl